# 開発モードのアプリ起動用 コンテナ イメージ
#
# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /app
 
# copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore
 
# copy everything else and build app
COPY . ./
RUN dotnet build --no-restore
 
# create builtin database
RUN dotnet tool install dotnet-ef --tool-path=/usr/local/bin
RUN dotnet ef migrations add InitialCreate
RUN dotnet ef database update

ENTRYPOINT ["dotnet", "run", "--no-build", "--urls",  "http://*:5000"]